### ISSUE TITLE
Cover Microsoft Azure in matrix

### ISSUE THREAD

**Issue by jlevy** [open-guides/og-aws#1]
Most of these entries currently missing.

**Comment by itaysk** [comment]
Is there any help still required after PR #96 ?

**Comment by kimschmidtsbrain** [comment]
2 years ago I did a comparison of Azure, AWS & GCP for the Physicians Insurance Association of America. Been 2 years, but can help if needed. At the speed of rapid change, what I know from then would need major updating.

**Comment by jlevy** [comment]
I think #96 brings us to where this can be closed. However, if either of you have additional entries, do PR!
