### ISSUE TITLE
Microsft Azure description

### ISSUE THREAD

**Issue by itaysk** [open-guides/og-aws#104]
The way you described Microsoft Azure under "🚪AWS vs. other cloud providers" as a good fit for only existing Microsoft shops is a little diminishing. Would you be willing to consider changing that text?
I know this is almost 'off topic' since the goal of this doc is to be an AWS guide and not a comparison between providers, but if there's going to be any reference there, at least let's try to make it objective, right?

(Why I think that statement is wrong)
Microsoft is [very invested in Open Source][1] and Azure is the best example for that. I would argue that in some scenarios Azure is better that others even for non-MS workloads. In terms of market competition, [Gartner puts Azure ahead of GCP both in Vision and Execution][2] so the implicit comparison there ("The most significant direct competitor") should be rephrased in my opinion . 

Disclaimer: I'm a Microsoft employee

[1]: http://www.businessinsider.com/microsoft-github-open-source-2016-9
[2]: https://www.gartner.com/doc/reprints?id=1-2G2O5FC&ct=150519&st=sb

**Comment by jlevy** [comment]
Believe this is now fixed with #111. If you think further changes are needed, do let us know or file another issue.
