### ISSUE TITLE
Addition for route53

### ISSUE THREAD

**Issue by vincent-dm** [open-guides/og-aws#107]
A gotcha for me was that a hosted zone and a domain name are something different in Route53. Because they are created together automatically when buying/transfering a domain through AWS, it is not clear that your domain is the place where you configure nameservers, which should correspond with the NS record of any Hosted Zone (can be in another account).

I use my bastion account to keep the registry of domains (since they are of critical importance to our business), but I use the app accounts to manage the hosted zones.

**Comment by jlevy** [comment]
@vincent-dm seems like a fair point to explain. Would you be up for filing a PR with this (stated very briefly, ideally with a link or two) in the Route 53 tips section?

**Comment by vincent-dm** [comment]
Alright, I created a pull request: https://github.com/open-guides/og-aws/pull/318

**Comment by jlevy** [comment]
Fixed in #318
