### ISSUE TITLE
Basic coverage (and editor) for Elastic Beanstalk

### ISSUE THREAD

**Issue by jlevy** [open-guides/og-aws#127]
First draft of the basics of what it does and when to use. Can expand later.

Need an editor, too.

**Comment by lynnlangit** [comment]
I can take this one, if needed.  LMK

**Comment by pgrzesik** [comment]
Is someone working on basic overview of Elastic Beanstalk ?

**Comment by QuinnyPig** [comment]
It’s you. Go for it!

**Comment by kevinslin** [comment]
just submitted a pull request. first time contributing to this project so please let me know if anything is off
