### ISSUE TITLE
S3 correction about us-east-1 region

### ISSUE THREAD

**Issue by jlevy** [open-guides/og-aws#179]
This item is out of date, as has been brought to our attention by AWS.

> Hello,
>  
> I am writing to you as contributors to this github repository to ask that you make a correction to “The Open Guide to Amazon Web Services” - https://github.com/open-guides/og-aws#s3-basics
>  
> The section below is no longer true.  S3 is no longer replicated across coast.  That is why us-east-1 now has the same consistency model as all other regions and the latency has been reduced AWS has updated our documentation to reflect this change.  Can you please remove this section?  We want the right information out there.
>  
> Section that should be removed:
> US Standard region: Most S3 endpoints match the region they’re in, with the exception of the us-east-1 region, which is called 'us-standard' in S3 terminology. This region is also the only region that is replicated across coasts. As a result, latency varies more in this region than in others. You can minimize latency from us-east-1 by using s3-external-1.amazonaws.com.
>  
> Thanks for your time,
>  
> Lee
> 
> Lee Kear
> Storage Specialist Solutions Architect
> Amazon Web Services

**Comment by jlevy** [comment]
I think it's best not to delete entirely, but just to note the history, as many of us well remember this problem. "Previously, the us-east-1 region was replicated across coasts, which led to greater variability of latency. This is _no longer the case_." Ideally with links.

Mr @max-zanko do you agree? over to you on this? :)

**Comment by ThanosBaskous** [comment]
FWIW I agree that we should have a note that maintains the historical behavior and issue - it makes it easier to square what is said in the guide with what readers might see in older tutorials and blog posts around the internet.
