### ISSUE TITLE
Correction: 2015 AWS revenue

### ISSUE THREAD

**Issue by nickflawler** [open-guides/og-aws#194]
2015 AWS revenues were $7.88 billion. 7.4% of Amazon's total revenues but 41% of operating profits.
http://phx.corporate-ir.net/phoenix.zhtml?c=176060&p=irol-newsArticle&ID=2133284

**Comment by kimschmidtsbrain** [comment]
Interesting, got different numbers from another source. Thank you for this, I'll try to confirm your statement!!!

**Comment by jlevy** [comment]
For sure, we should correct/update. Thanks @nickflawler @kimschmidtsbrain ! If anyone has other info let us know, but assume a press release from Amazon is the best source to link to.

**Comment by kimschmidtsbrain** [comment]
Getting stats that can be shared today/tomorrow.

Sincerely,

Kim Schmidt
949-735-8505
@DataLeader, @WearableQueen
https://www.linkedin.com/in/kimschmidt1

**Comment by rjhintz** [comment]
[SEC 10-K](http://phx.corporate-ir.net/phoenix.zhtml?c=97664&p=irol-sec&control_selectgroup=Annual%20Filings) filing corroborates @nickflawler's number of $7.88B for 2015 net sales/revenue.
