### ISSUE TITLE
Cover deploy frameworks (Asgard, Spinnaker, etc)

### ISSUE THREAD

**Issue by jlevy** [open-guides/og-aws#23]
At least mention major ones and who uses them, etc.
https://github.com/Netflix/asgard
http://www.spinnaker.io/

**Comment by rjhintz** [comment]
@jlevy Where do you see this fitting into the README file? I might start a branch outlining candidate entries, but I want to put it where you see fit.
cc @ThanosBaskous

**Comment by jlevy** [comment]
Closing and including with #317
