### ISSUE TITLE
AWS CLI support AWS Certificate Manager since version 1.10.0

### ISSUE THREAD

**Issue by number5** [open-guides/og-aws#232]
In https://github.com/open-guides/og-aws#aws-product-maturity-and-releases it stated AWS Certificate Manager don't have CLI support, but it's actually supported (via `aws acm` command) since awscli 1.10.0

See https://github.com/aws/aws-cli/blob/master/CHANGELOG.rst#1100

**Comment by raajheshkannaa** [comment]
@number5 Good catch. I've sent a pull request with the change. Thank You.
