### ISSUE TITLE
Link to AWS books

### ISSUE THREAD

**Issue by jlevy** [open-guides/og-aws#243]
From @abdulirfan3 : 

Amazon Web Services in Action
Serverless Single Page Apps
AWS Lambda in Action
The Terraform Book (availabe late 2016)
Python and AWS Cookbook(this one is old, but still valid)

What others?

**Comment by kimschmidtsbrain** [comment]
1. You can get these neat little books on most services and more at Amazon.com **FREE**. Type in the search bar "AWS Books" and you'll get a list. They're all electronic format (ie, Kindle, etc.). They give you the basics + a walk-through of using it. Example: https://www.amazon.com/CloudFormation-User-Guide-Amazon-Services-ebook/dp/B007S28IUW/ref=sr_1_11?ie=UTF8&qid=1477167075&sr=8-11&keywords=AWS+Books 

2. Bash Pocket Reference ISBN: 978-1-491-94159-1

3. AWS Scripted: ISBN: 9781503137776

**Comment by jlevy** [comment]
Most of these are in place, but would be good to have an owner for this section.

@kimschmidtsbrain 's book suggestion looks worth mentioning:
https://www.amazon.com/AWS-Scripted-Automate-Deployment-Resilient/dp/1503137775

**Comment by abdulirfan3** [comment]
@jlevy 

I can take ownership of this, but could you please point me where/what section to put this under and I can file a PR.

**Comment by jlevy** [comment]
@abdulirfan3 Cool. This is where the section is:
https://github.com/open-guides/og-aws#further-reading

The bullets (blogs, books, etc) there should be broken out as subsections (so we can link to them) and any additional books should be listed.

Appreciate if you can discuss/chat in Slack as needed to identify any other books too!

**Comment by QuinnyPig** [comment]
Closing this issue, as there's now a section for it. Yay!
