### ISSUE TITLE
More on when Certificate Manager works

### ISSUE THREAD

**Issue by jlevy** [open-guides/og-aws#257]
From discussion w @lynnlangit in #253 

> We should probably add that AWS Manager only works with Elastic Load Balancer and Cloud Front. Also that AWS IoT has a its own process for creating and managing certificates intended to be used with IoT devices. The latter servers as authorization and authentication (via IoT policies) for specific IoT devices to send device messages via MQTT to a particular AWS IoT Device Gateway (endpoint).

These could be separate points. This might be moved/consolidated with the current point about "Certificates issued by the **Certificate Manager** can't be used outside of the services that support it. Imported certificates, however, can still be used elsewhere." in a new Limitations and Gotchas subsection.

**Comment by artemnikitin** [comment]
I will do it.

**Comment by artemnikitin** [comment]
Looks like this ticket can be closed. The related change was merged long ago.

**Comment by ThanosBaskous** [comment]
Thanks @artemnikitin!
