### ISSUE TITLE
Amazon Product Advertising API

### ISSUE THREAD

**Issue by ISchwarz23** [open-guides/og-aws#269]
Hi all,

as I had to use the Amazon Product Advertising API, I have realized that there is no support for this in the official amzon-java-sdk. Therefor I have created a simple library that helps developers the create and signe the request URLs for the PA-API. (You can find it https://github.com/ISchwarz23/Amazon-Product-Advertising-API-URL-Builder)

Would it be helpful to mention this library in your docs, so other devs don't have to solve the same issues I already solved?

Best regards,
Ingo

**Comment by ThanosBaskous** [comment]
Hi @ISchwarz23, thanks for filing this for discussion. I think that your library looks useful - something that I would consider trying if I ever ran into the same problem - but I think that it isn't right for inclusion in the guide right now. We are trying to ensure that most / all library mentions in the guide are well accepted / "standard" solutions to an AWS problem - down the line, if it gets some traction, I would support linking it as a part of a tip or gotcha on the topic. Closing this for now, but happy to continue discussing.
