### ISSUE TITLE
Snowball was released Oct 2015

### ISSUE THREAD

**Issue by AstroTom** [open-guides/og-aws#322]
Snowball was released in oct 2015 (https://aws.amazon.com/about-aws/whats-new/2015/10/aws-import-export-snowball/)
not as you have in your table

**Comment by ThanosBaskous** [comment]
Good catch @AstroTom! Are you willing to submit a PR? If not, I'll find someone else (or do it myself).

**Comment by lobster1234** [comment]
@QuinnyPig @ThanosBaskous can this issue be closed? The PR has been merged.

**Comment by ThanosBaskous** [comment]
Good catch, @lobster1234. Closing.

**Comment by ThanosBaskous** [comment]
Good catch, @lobster1234. Closing.

**Comment by ThanosBaskous** [comment]
Good catch, @lobster1234. Closing.
