### ISSUE TITLE
AWS Lambda now supports environment variables

### ISSUE THREAD

**Issue by wamoyo** [open-guides/og-aws#328]
Hey now! https://aws.amazon.com/about-aws/whats-new/2016/11/aws-lambda-supports-environment-variables/

How cool is that?

Just remove the gotcha I suppose?  https://github.com/open-guides/og-aws#lambda-gotchas-and-limitations

**Comment by anilgkurian** [comment]
That's cool

**Comment by ThanosBaskous** [comment]
Excellent (and yiassou, Costa)! Would you be willing to submit a PR? Not a big deal if not - in that case, I'll pick it up.

**Comment by wamoyo** [comment]
@ThanosBaskous Για σου, Θαναση! Wow, Greeks on GitHub. Who would have thought : ) 

I would love to submit a pull request! I have yet to do that on GitHub, are you willing to help me get it right? I'll google around, but I might need some help.
