### ISSUE TITLE
IoT coverage

### ISSUE THREAD

**Issue by jlevy** [open-guides/og-aws#35]
Links of interest:
http://www.slideshare.net/ServerlessConf/ben-kehoe-serverless-architecture-for-the-internet-of-things
https://github.com/awslabs/aws-iot-examples

**Comment by jlevy** [comment]
Items to cover (thanks to @benkehoe ):
IoT is really a pub/sub system that is applicable to IOT but useful in lots of situations.
Could build chat service on top of IOT.
Has free computation. Rules engine has free computation. If you can make your whole chat client in IOT you don't pay for any of that logic.

**Comment by jlevy** [comment]
@benkehoe @lynnlangit :

These were some notes I had from a convo with Ben a while back. Lynn has since created a whole IoT section.

Ben, maybe you'd be up to reviewing/giving feedback?

And Lynn, Ben has a bunch of experience using IoT, so hope these notes or his feedback can help.

Thanks to you both!

**Comment by jlevy** [comment]
Let's close this issue once you guys confer and decide on additions (if any).

**Comment by lynnlangit** [comment]
I haven't got any other feedback here - is this closed now?

**Comment by jlevy** [comment]
I'll close as we do now have a good section. We can take discussion to Slack.
