### ISSUE TITLE
Resource to harden AMIs before being put on AWS Marketplace

### ISSUE THREAD

**Issue by Omnipresent** [open-guides/og-aws#361]
I have not been able to find any resource that practically shows how to harden an AMI before putting it on the Marketplace. 

This guide from Amazon doesn't present much https://aws.amazon.com/articles/9001172542712674

Would appreciate additional resources.

**Comment by thildebrant** [comment]
They provide a guide when you register as a marketplace "seller". Also available to partners I believe.

**Comment by Omnipresent** [comment]
I'm logging into the seller marketplace portal but don't see anything. Do you have a resource handy?

**Comment by Omnipresent** [comment]
Found this https://aws.amazon.com/articles/0155828273219400

**Comment by thildebrant** [comment]
Google search gives me http://awsmp-loadforms.s3.amazonaws.com/AWS_Marketplace_-_Seller_Guide.pdf 
Though it's marked confidential for sellers only

**Comment by thildebrant** [comment]
I don't know if we should rely on that link as it's super focused on the marketplace. Rather a better path would be on how to secure AMIs in general.

**Comment by Omnipresent** [comment]
I agree with that approach.

**Comment by QuinnyPig** [comment]
Closing this issue for now; feel free to reopen it if anyone has a good example.
