### ISSUE TITLE
Mention an AZ is separate physical infra

### ISSUE THREAD

**Issue by jlevy** [open-guides/og-aws#385]
From discussion — let's mention/link this as it's a common question.

thanos [9:43 AM] 
From https://www.youtube.com/watch?v=JIQETrFC_SQ&feature=youtu.be&t=1428
"An availability zone is 100% always without ever an exception, a completely independent building. It is a different datacenter."

**Comment by DavidTPate** [comment]
It would be good to mention also that there is low latency between AZs. This was taken from the docs:

> Availability Zones are physically separate, such that even extremely uncommon disasters such as fires, tornadoes or flooding would only affect a single Availability Zone.
> Although Availability Zones within a Region are geographically isolated from each other, they have direct low latency network connectivity between them.
