### ISSUE TITLE
SSL certificate on og-aws-slack.lexikon.io expired on 2017-04-17

### ISSUE THREAD

**Issue by trenton** [open-guides/og-aws#429]
Appears to have expired on 2017-04-17

<img width="986" alt="screen shot 2017-04-21 at 12 08 24 am" src="https://cloud.githubusercontent.com/assets/140476/25266645/bdc60d5c-2626-11e7-99af-df6b6d897c23.png">

**Comment by ThanosBaskous** [comment]
@jlevy can you take a look at this when you get a chance?

**Comment by jlevy** [comment]
Yes, fixed. Switched to an ACM cert so hopefully the buggy renew process will now be avoided. :P

**Comment by jlevy** [comment]
Thanks @trenton for reporting!

**Comment by ThanosBaskous** [comment]
Thanks for fixing, @jlevy! Thanks for reporting, @trenton!

**Comment by trenton** [comment]
Confirmed it working. Was able to join the channel tonight. Thanks for the fix.
