### ISSUE TITLE
Flag HIPAA-compliant services

### ISSUE THREAD

**Issue by ThanosBaskous** [open-guides/og-aws#445]
Flag services that are HIPAA-compliant - one idea would be to add a column in the "AWS Product Maturity and Releases" section.

https://aws.amazon.com/compliance/hipaa-eligible-services-reference/
https://aws.amazon.com/about-aws/whats-new/2017/06/cloudfront-s3-transfer-acceleration-waf-shield-are-now-hipaa-eligible/

**Comment by jlevy** [comment]
👍 good idea

**Comment by geekmuse** [comment]
Could this possibly be expanded to include PCI-compliant services as well?

**Comment by QuinnyPig** [comment]
Closing. It's in the guide now; piecemeal updates are welcome!
