### ISSUE TITLE
Machine Learning on AWS

### ISSUE THREAD

**Issue by lynnlangit** [open-guides/og-aws#466]
A small group of us are working on a short guide to ML on AWS via a shared Quip document.  If you have domain expertise and would like to join LMK

**Comment by niranjv** [comment]
I would like to help. How can I start?

**Comment by lynnlangit** [comment]
@jlevy would it be possible for you to invite @niranjv to our shared Quip document?  -- thanks

**Comment by jlevy** [comment]
@lynnlangit sorry for delay; looks like it's your doc and you've disabled sharing on the doc — can you enable link sharing? (Quip is a bit confusing on this. :( )

**Comment by jlevy** [comment]
@niranjv in any case can you ping me (jlevy) in the Slack group and we'll sort it out? There are a few areas for ML coverage where your help would be super appreciated.

**Comment by jlevy** [comment]
@lynnlangit sorry for delay but  https://quip.com/hmAKA6bCQPy0

**Comment by niranjv** [comment]
@jlevy @lynnlangit Thanks for granting me access to the doc. Now how do I get started? Is there any specific item I can work on?

**Comment by lynnlangit** [comment]
I've been framing cloud-based ML in terms of two offer types - serverless APIs (i.e. Vision, Speech, etc...) and custom model hosting (both regular and dnns, such as MxNet, Tensorflow etc...).  I would start by reframing the existing document this way.  Also I think comparisons to other cloud vendors, particularly GCP ML offerings is important.
