### ISSUE TITLE
S3 "gotcha" on naming about causing issues with automation is not entirely accurate

### ISSUE THREAD

**Issue by rdymek** [open-guides/og-aws#469]
Within S3, under the "Key Prefixes" section, there is a statement: "🔸Note that sadly, the advice about random key names goes against having a consistent layout with common prefixes to manage data lifecycles in an automated way."

This is not true, in that lifecycles can have wildcards. And since S3 is a flat filesystem anyhow, and this randomization to create entropy does not affect that. Some examples:

mybucket/xdbvsd/myfolder1/subfolder/mydata.txt
mybucket/bkdscf/myfolder2/subfolder/mydata2.txt
mybucket/lsbies/myfolder1/subfolder/mydata3.txt
mybucket/13kszk/myfolder1/subfolder/mydata4.txt

In this example I have a 6 character random string as the first part of the object key. if I wanted to create lifecycles, my lifecycle prefix could be something like: */myfolder1/subfolder/mydata?.txt

Automation is perfectly fine here, the only thing that randomizing does is breaks human readability since if you log into the web console objects will no longer be in the proper "folders". So you loose lexigraphical order and alphabetical order but thats really just human readability and works fine for situations where you want automated actions against s3. Adding in a secondary index (dynamodb?) for your data in s3 is a common practice as well, and not mentioned that I can see - this would be a huge help as well for automation against these randomized object names.

**Comment by rdymek** [comment]
It takes 30 seconds to verify that it does use wild cards, and has been for
years!

**Comment by QuinnyPig** [comment]
Let's keep things friendly here, please.

It's extraordinarily difficult to test a lifecycle rule in less than a minute. :)

Everything I'm reading from AWS shows that wildcards aren't supported, and I'm not able to get a working lifecycle rule with wildcards in it. What am I missing here?

**Comment by rdymek** [comment]
I have to apologize, as I knew I was doing wildcards with LIfecycles but it turns out "how" I was doing it was not directly using wildcards. First, to clear this up - I was wrong in my initial statement in that you actually cannot directly use wildcards specifically in lifecycle policies, so I stand corrected there. The way I am doing it is to tag the data. You can in fact tag data via wildcards and various automated methods. Then you can use lifecycle rules to work with tags. So maybe just simply expanding on this statement describing some methods like that as "workarounds" would be good. But ultimately, I suppose the statement is accurate - though workable.
