### ISSUE TITLE
Incorrect statement Re: Cloud Formation template rollback

### ISSUE THREAD

**Issue by ayybe** [open-guides/og-aws#487]
Since Feb 2016, you can rollback your own stuck CFN stacks without contacting support: 

Continue Rolling Back an Update for AWS CloudFormation stacks in the UPDATE_ROLLBACK_FAILED state
https://aws.amazon.com/blogs/devops/continue-rolling-back-an-update-for-aws-cloudformation-stacks-in-the-update_rollback_failed-state/

**Comment by julienduchesne** [comment]
Using the CLI (can't do it in the console I think), you can also skip problematic resources. 
http://docs.aws.amazon.com/cli/latest/reference/cloudformation/continue-update-rollback.html
-resources-to-skip (list)
