### ISSUE TITLE
Scalr link 404s

### ISSUE THREAD

**Issue by baynezy** [open-guides/og-aws#520]
The link to Scalr in [README.md](https://github.com/open-guides/og-aws/blame/master/README.md#L809) now 404s. I don't know if it has been renamed or removed.

This is the [old content](https://webcache.googleusercontent.com/search?q=cache:KPBj4vDcMuMJ:https://github.com/Scalr/scalr+&cd=1&hl=en&ct=clnk&gl=uk).

@em0ney - you added it. Do you know the story?

**Comment by ThanosBaskous** [comment]
Thanks @baynezy! Addressed by @QuinnyPig in #519.
