### ISSUE TITLE
Where can I donate?

### ISSUE THREAD

**Issue by davidjeddy** [open-guides/og-aws#578]
This is amazing! Blown away with the depth and breadth of information here! :takemymoney:
Where can I donate / give support?

**Comment by QuinnyPig** [comment]
Thanks!  

Feel free to submit PRs— content reigns supreme!

**Comment by davidjeddy** [comment]
Nono, I mean: 
![382f90313fde253278147683a666aa27c79a4cdaa57791c383b1ad1f01d4bd26](https://user-images.githubusercontent.com/6232455/34681765-d921fc60-f46a-11e7-85fe-01bb3259fa75.jpg)
