### ISSUE TITLE
Request : Requirement is - Highly available configuration of ArcGIS Portal, Server, and DataStore (Windows).

### ISSUE THREAD

**Issue by sourav1985** [open-guides/og-aws#589]
## Request : Requirement is - Highly available configuration of ArcGIS Portal, Server, and DataStore (Windows).
- [ ] Bug
- [ ] New Feature
- [ ] Refactor
- [X ] Question 
- [ ] Documentation
- [ X] Tests  
- [ ] Other

## Details
* ...

**I was working on this issue and I got struck so , I was going though some of the documents there is a AWS templets closely matching to the requirement   .... will any of you have some time to look in to it?  Please share suggestions you might have. I am not able to run it or improvement plan if you have any** 

Requirement is - Highly available configuration of ArcGIS Portal, Server, and DataStore (Windows).
![image]

(https://user-images.githubusercontent.com/30665725/36354522-df1806c6-14fb-11e8-8453-053820df71db.png)

Code : [Text.txt](https://github.com/bonusbits/cloudformation_templates/files/1734903/Text.txt)

**Comment by maishsk** [comment]
Hi @sourav1985 is there something in the documentation missing?

If you have a question that you would like an answer for  - you can [join the Slack channel](https://og-aws-slack.lexikon.io/) - and ask it there.

Do you have any objections to closing out this issue?

**Comment by maishsk** [comment]
Thanks!
