### ISSUE TITLE
Live streaming using AWS MediaLive and MediaPackage.

### ISSUE THREAD

**Issue by Viv3k** [open-guides/og-aws#597]
Im trying to live stream content using Amazon AWS MediaLive and MediaPackage. I have configured android app to push data to MediaLive  (we also tried the pull flow) from a RTMP stream generated by an android app (app pushes to endpoint generated by MediaLive).

MediaLive shows 'Network In' and 'Network Out' however 'Ingress' and 'Egress' activity of MediaPackage shows empty values. I did provide credentials of MediaPackage channels in MediaLive output groups.

Also verified the credentials used in the MediaLive are correct. Would be great if someone could hint to a solution or an alternative.

Thanks.

**Comment by maishsk** [comment]
@Viv3k I think that you would get a speedier response if you would ask this in the Slack channel.

Do you still want this issue left open?

**Comment by Viv3k** [comment]
@maishsk You can go ahead and close the issue.
