### ISSUE TITLE
Amazon Aurora is 5.7 version compatible now

### ISSUE THREAD

**Issue by limay** [open-guides/og-aws#624]
The gotcha described here https://github.com/open-guides/og-aws#rds-aurora-gotchas-and-limitations is obsolete now, as new Mysql Aurora instances can be created with MySQL 5.7 version compatibility.

**Comment by maishsk** [comment]
@limay I don't see that the link you posted works - is this still an issue?

**Comment by limay** [comment]
Sorry, this link goes exactly to the problem: https://github.com/open-guides/og-aws#rds-aurora-mysql-tips

The only change is that now you can have MySQL 5.7 version compatibility on Aurora, so the mentioned problems should not be anymore.
