### ISSUE TITLE
Bug with spaces at the end of Tag keys

### ISSUE THREAD

**Issue by AstroTom** [open-guides/og-aws#625]
(I tried to add this directly in the  "General Visibility"  section with a pull request, but I guess I do not have permission.)

Tags Gotcha:
There is a bug in the ASG console where spaces after tag names are preserved. So if you type "Name " with an extra space at the end you will not get the expected behavior. This is probably true in other locations and SDKs also. Be sure you do not add trailing spaces to tag keys unless you really mean it.

**Comment by DavidTPate** [comment]
@AstroTom You'll need to fork the repository (ie. make your own copy) then make your changes and open a PR. There's a [decent guide](https://gist.github.com/Chaser324/ce0505fbed06b947d962) in the Gist I linked if you want to give it a try.

**Comment by maishsk** [comment]
@AstroTom  should be closed - I see that https://github.com/open-guides/og-aws/pull/621 was merged..

**Comment by maishsk** [comment]
Closing  was merged in #621
