### ISSUE TITLE
Terminology: ELB, ALB, CLB

### ISSUE THREAD

**Issue by jlevy** [open-guides/og-aws#70]
Seems like AWS' usage is now that ELBs are the overall class and they are now divided into Classic and Application LBs. Should we switch to use CLB and ALB everywhere?

**Comment by ThanosBaskous** [comment]
That seems correct, but it's probably worth including a note about the historical use of the term (since lots of references / blog posts / etc. will probably continue to use "ELB" to refer to what is now the "CLB".)

**Comment by jlevy** [comment]
Yeah agreed.
