### ISSUE TITLE
data transfer cost cross az

### ISSUE THREAD

**Issue by liuchenggang2014** [open-guides/og-aws#715]
![data transfer cost](https://user-images.githubusercontent.com/7160463/64160641-dbbf9100-ce6e-11e9-9663-7279916af3b9.png)

here is the offical document from "https://aws.amazon.com/ec2/pricing/on-demand/":

""Data transferred "in" to and "out" from Amazon EC2, Amazon RDS, Amazon Redshift , Amazon DynamoDB Accelerator (DAX), and Amazon ElastiCache instances or Elastic Network Interfaces across Availability Zones or VPC Peering connections in the same AWS Region is charged at $0.01/GB in each direction."

the data transfer cost should be single direction, so in the picture No.5, should be 0+0.01 instead of 0.01+0.01 in each direction.

**Comment by mignaulo** [comment]
You get billed 0.01 at AZ A for sending, then 0.01 at AZ B for receiving - 0.01 + 0.01 per direction - I think the graph is correct.
