### ISSUE TITLE
How can I join the og-aws Slack channel? The link is obsolete.

### ISSUE THREAD

**Issue by JoshuaFox** [open-guides/og-aws#766]
There is a link in the Readme, but this "shared invitation" is no longer active. How can I join?

**Comment by rishabh96b** [comment]
Looks like it is working. Check this out: 
[Join og-aws](https://og-aws.slack.com/join/shared_invite/enQtOTUwMjQzOTkyNTI5LTZkNDNjMTAyZDU1ZjQ1ZTU2NjBiZGVmOGJiN2Y2MjEzM2ZlZWEyMGIwNzUzNTJlMzM5YmY3Yzg3MTRiMGE0NjI#/)

**Comment by JoshuaFox** [comment]
Thank you. I succeeded in connecting (through http://slackhatesthe.cloud)

**Comment by acsrujan** [comment]
Can be closed post: #767
