### ISSUE TITLE
Please how can i use aws lambda to launch firefox

### ISSUE THREAD

**Issue by Afoxcute** [open-guides/og-aws#776]

**Comment by maishsk** [comment]
Thanks for opening the issue.

Can you please explain more about what you are trying to achieve - and if this is an issue with the information in the repo? 

If not - it would be better to raise you question in the slack and no here as an issue on the repo.

**Comment by Afoxcute** [comment]
thanks for your response @maishsk. Actually, i am trying to use was lambda to launch firefox and firefox should visit a website. Nothing fancy.

**Comment by maishsk** [comment]
So I am going to close this out - because this would be better to ask someone in the [Slack channel](http://slackhatesthe.cloud/) and not something that we will address as part of the repo.

**Comment by maishsk** [comment]
So I am going to close this out - because this would be better to ask someone in the [Slack channel](http://slackhatesthe.cloud/) and not something that we will address as part of the repo.
