### ISSUE TITLE
Slack link is no longer active and needs update

### ISSUE THREAD

**Issue by vasili111** [open-guides/og-aws#797]
Could you please update slack invite link? It is no more active and needs update. 

![image](https://user-images.githubusercontent.com/7338799/152654505-855994db-e884-4249-b182-c58f6bcca94a.png)

![image](https://user-images.githubusercontent.com/7338799/152654534-c8b24a5d-e7fc-4cf2-acdb-70f488fb4ef3.png)

**Comment by dgokcin** [comment]
I also would like to join the channel and confirm that the link is not working. Any help is appreciated.

**Comment by QuinnyPig** [comment]
Slack link expired. Refreshed; sorry for the trouble!
