### ISSUE TITLE
Note about s3 "random key names"

### ISSUE THREAD

**Issue by rokka-n** [open-guides/og-aws#86]
"🔸Note that sadly, the advice about random key names goes against having a consistent layout with common prefixes to manage data lifecycles in an automated way."

I think these are two different problems: s3 performance and object lifecycle management. 

I think in general the guide should to be less biased about particular implementations and concentrate solely on Amazon's services pros and cons.

**Comment by jlevy** [comment]
The intended point is that you can't have randomness on the start of a key, as well as folder-based lifecycles. You have to pick.

Perhaps you can clarify the concern? This isn't a bias as much as an observation that you can't do both, given S3's design.

**Comment by rokka-n** [comment]
Maybe reference to amazon's doc about performance optimization would be useful in this case?
http://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html

There is still a way to have keys prefixed with some sort of naming scheme and have hashes added after, it is mentioned in that guide. So lifecycle rules can be configured based on prefixes (example from aws s3 cli guide):
```
{
  "Rules": [
    {
      "ID": "Move to Glacier after sixty days (objects in logs/2015/)",
      "Prefix": "logs/2015/",
      "Status": "Enabled",
      "Transition": {
        "Days": 60,
        "StorageClass": "GLACIER"
      }
    },
    {
      "Expiration": {
        "Date": "2016-01-01T00:00:00.000Z"
      },
      "ID": "Delete 2014 logs in 2016.",
      "Prefix": "logs/2014/",
      "Status": "Enabled"
    }
  ]
}
```

It's probably the best when objects keys are completely random with the metadata information stored in low latency storage systems like dynamodb. Then lifecycle management can be applied easily and consistently to all objects in a bucket.

**Comment by jlevy** [comment]
Based on the explanation offered from AWS on partitioning, in the situation where you have high qps and large numbers of keys, adding the fixed prefixes _could_ have a performance penalty when compared with keys starting with the full randomness (as is the preferred examples in that link). But partitioning seems to be dynamic, too, so it may not be the case. Do you have any concrete perf observations when using prefixes + hashes?

@max-zanko suggests using multiple buckets in this case to support the lifecycle management + high perf. That approach seems safe.

We could elaborate this bullet a little. PR welcome.

**Comment by rokka-n** [comment]
👍 good stuff
